load("@rules_cuda//cuda:defs.bzl", "cuda_test")

package(default_visibility = ["//visibility:private"])

CUDA_SANITIZER_COMPATIBILITY = select({
    "//:asan_enabled": ["@platforms//:incompatible"],
    "//conditions:default": [],
}) + select({
    "//:ubsan_enabled": ["@platforms//:incompatible"],
    "//conditions:default": [],
})

cuda_test(
    name = "smoke_test",
    size = "small",
    srcs = ["smoke_test.cu"],
    copts = ["-std=c++20"],
    tags = [
        "manual",
        "requires-gpu",
    ],
    target_compatible_with = CUDA_SANITIZER_COMPATIBILITY,
    visibility = ["//visibility:public"],
)
